# CHEN 2450 - Coding Activity 4
# Jacobi Iterative Solver
## Prof. Tony Saad

Use the Jacobi iterative solver to find the solution of the following system of equations:
\begin{equation}
\begin{bmatrix}
5 & 1 & 1\\ 
2 & 3 & 0\\ 
3 & 0 & 4
\end{bmatrix}
\begin{pmatrix}
x_1\\ 
x_2\\ 
x_3
\end{pmatrix}
=
\begin{pmatrix}
10\\ 
11\\ 
12
\end{pmatrix}
\end{equation}

Below is an implementation of the Jacobi iterative solver

$$
x_i = x_{guess, i}+\frac{b_i \mathbf{a}_i \mathbf{x}_{guess}}{a_{i i}}
$$

In [21]:
import numpy as np
from numpy.linalg import norm

def jacobi(A, b, xguess, maxIter):
    
    # Make sure A is a numpy array
    A = np.array(A)
    [num_rows, num_cols] = A.shape
    
    iter = 0 # counter
    x  = np.zeros(num_rows) # declare x array
    
    while (iter < maxIter):
        
        # loop over the rows
        for i in range(0, num_rows):
            x[i] = xguess[i] + (b[i] - A[i]@xguess)/A[i][i]
            
        #make sure x and xguess are NOT the same
        xguess = x.copy()
        iter +=1
    return x

Define your coefficient matrix, RHS, initial guess, and max iterations

In [22]:
A = [[5,1,1],
     [2,3,0],
     [3,0,4]]
b = [10,11,12]
x0 = [1,1,1]
maxIter = 10

Now call the Jacobi solver to solve this system of equations

In [23]:
jacobi(A,x0,b,maxIter)

array([0.13432623, 0.27521746, 0.18461964])

To gain more insight into what the solver is doing, modify the Jacobi routine to print out iteration number and the value of each iterate $x_i^k$

In [18]:
def jacobi2(A,b,xguess,maxIter):
    # Make sure A is a numpy array
    A = np.array(A)
    [nr,nc] = A.shape
    iter = 0 # counter
    x  = np.zeros(nr) # declare x array
#     ????
    while (iter < maxIter):
        print(x, iter)
        # loop over the rows
        for i in range(0,nr):
            x[i] = xguess[i] + 1.0/A[i][i] * (b[i] - A[i]@xguess)
        #make sure x and xguess are NOT the same
        xguess = x.copy()
        iter +=1
    return x

In [19]:
A = [[5,1,1],
     [2,3,0],
     [3,0,4]]
b = [10,11,12]
x0 = [1,1,1]
maxIter = 10

In [20]:
jacobi2(A,x0,b,maxIter)

[0. 0. 0.] 0
[-4.4        -6.33333333 -7.25      ] 1
[2.91666667 3.26666667 3.55      ] 2
[-1.16333333 -1.61111111 -1.9375    ] 3
[0.90972222 1.10888889 1.1225    ] 4
[-0.24627778 -0.27314815 -0.43229167] 5
[0.34108796 0.49751852 0.43470833] 6
[ 0.01355463  0.10594136 -0.00581597] 7
[0.17997492 0.32429691 0.23983403] 8
[0.08717381 0.21335005 0.11501881] 9


array([0.13432623, 0.27521746, 0.18461964])

Now experiment with different maximum iterations - what do you observe?

Clearly, we need a way to tell the solver to stop. A tolerance is useful in this case. Add an error measure to the Jacobi routine so that the solver stops at a certain tolerance.

In [24]:
def jacobi3(A,b,xguess,tol):
    # Make sure A is a numpy array
    A = np.array(A)
    [nr,nc] = A.shape
#     ??????
    iter = 0 # counter
    x  = np.zeros(nr) # declare x array
    
    while (error > tol):
        
        # loop over the rows
        for i in range(0,nr):
            x[i] = xguess[i] + 1.0/A[i][i] * (b[i] - A[i]@xguess)

#         ????
        #make sure x and xguess are NOT the same
        xguess = x.copy()
        
        iter +=1
    return x

In [25]:
A = [[5,1,1],
     [2,3,0],
     [3,0,4]]
b = [10,11,12]
x0 = [1,1,1]
maxIter = 100


In [26]:
jacobi3(A,x0,b,maxIter)

NameError: name 'error' is not defined